---
# Kubernetes Secret Store - uses existing Kubernetes secrets as the source
# This is useful for migration or when secrets are managed externally
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kubernetes-secret-store
  namespace: flux-system
spec:
  provider:
    kubernetes:
      remoteNamespace: flux-system
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
