---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sources
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/sources
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-dapr
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/dapr
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dapr-operator
      namespace: dapr-system
    - apiVersion: apps/v1
      kind: Deployment
      name: dapr-sidecar-injector
      namespace: dapr-system
    - apiVersion: apps/v1
      kind: Deployment
      name: dapr-sentry
      namespace: dapr-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base/cert-manager
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/dev/infrastructure/traefik
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik
      namespace: traefik
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/dev/infrastructure/authentik
  prune: true
  wait: true
  decryption:
    provider: sops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authentik-server
      namespace: authentik
