---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: dapr
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
      interval: 12h
  releaseName: dapr
  targetNamespace: dapr-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      ha:
        enabled: false
      logAsJson: true
      registry: docker.io/daprio
    dapr_operator:
      replicaCount: 1
    dapr_sidecar_injector:
      replicaCount: 1
    dapr_sentry:
      replicaCount: 1
    dapr_placement:
      replicaCount: 1
