---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rocketchat
      version: 6.27.1
      sourceRef:
        kind: HelmRepository
        name: rocketchat
        namespace: flux-system
      interval: 12h
  releaseName: rocketchat
  targetNamespace: rocketchat
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mongodb:
    enabled: true
    auth:
      passwords:
        - rocketchat
      rootPassword: rocketchatroot

    microservices:
      enabled: true  # Enable microservices
    replicaCount: 1

    host: chat.dev.spoletum.net  # Replace with your Rocket.Chat domain
    ingress:
      enabled: true
      ingressClassName: nginx  # Specify the installed ingress controller in the K8s cluster
      annotations:
        cert-manager.io/cluster-issuer: letencrypt  # Replace with your ClusterIssuer name
      tls:
        - secretName: rocketchat-tls  # Use a different name if preferred
          hosts:
            - chat.dev.spoletum.net  # Replace with your Rocket.Chat domain