---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: 1.24.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  releaseName: tempo
  targetNamespace: tempo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Configure Tempo for single-instance with metrics generator
    tempo:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://prometheus-server.prometheus:80/api/v1/write"

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

      # Disable memberlist for single instance
      memberlist:
        enabled: false

    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
