---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo
      version: 1.24.4
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system
      interval: 12h
  releaseName: tempo
  targetNamespace: tempo
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Configure Tempo for single-instance mode
    tempo:
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
