---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2025.10.2
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
      interval: 12h
  releaseName: authentik
  targetNamespace: authentik
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: authentik-values
      valuesKey: values.yaml
