apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/components/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
    - name: infrastructure-cert-manager
    - name: infrastructure-traefik
  decryption:
    provider: sops
    secretRef:
      name: sops-age
