---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-loki
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/components/loki
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-sources
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: loki
          namespace: flux-system
        spec:
          values:
            lokiCanary:
              enabled: false
            test:
              enabled: false
      target:
        kind: HelmRelease
        name: loki
