---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tempo
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/components/tempo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
  patches:
    - patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: tempo
          namespace: flux-system
        spec:
          values:
            tempo:
              metricsGenerator:
                enabled: false
      target:
        kind: HelmRelease
        name: tempo
