---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tempo
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/components/tempo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-sources
  patches:
    - patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: tempo
          namespace: flux-system
        spec:
          values:
            tempo:
              metricsGenerator:
                enabled: true
                remoteWriteUrl: "http://prometheus-server.prometheus:80/api/v1/write"
            # Override config to add inmemory ring for metrics-generator
            config: |
              multitenancy_enabled: false
              usage_report:
                reporting_enabled: false
              compactor:
                compaction:
                  block_retention: 48h
              distributor:
                receivers:
                  otlp:
                    protocols:
                      grpc:
                        endpoint: 0.0.0.0:4317
                      http:
                        endpoint: 0.0.0.0:4318
              ingester: {}
              server:
                http_listen_port: 3200
              storage:
                trace:
                  backend: local
                  local:
                    path: /var/tempo/traces
                  wal:
                    path: /var/tempo/wal
              querier: {}
              query_frontend: {}
              metrics_generator:
                ring:
                  kvstore:
                    store: inmemory
                storage:
                  path: /var/tempo/generator/wal
                  remote_write:
                    - url: http://prometheus-server.prometheus:80/api/v1/write
                      send_exemplars: true
      target:
        kind: HelmRelease
        name: tempo
