---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: 0.x
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  releaseName: alloy
  targetNamespace: alloy
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Deploy as DaemonSet to run on every node
    alloy:
      mode: daemonset

      # Mount configuration from ConfigMap
      configMap:
        name: alloy-config
        key: config.alloy

      # Clustering disabled for DaemonSet mode
      clustering:
        enabled: false

    # Resource configuration
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

    # Service account with permissions to read pod logs
    serviceAccount:
      create: true

    # Enable RBAC for pod discovery and log reading
    rbac:
      create: true

    # Mount host paths for pod log access
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

    # Security context
    securityContext:
      privileged: false
      runAsUser: 0
      runAsGroup: 0
