---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nelcaso-core
  namespace: nelcaso
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: nelcaso-dapr-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nelcaso.dev.spoletum.net
      secretName: nelcaso-core-tls
  rules:
    - host: nelcaso.dev.spoletum.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nelcaso-core
                port:
                  number: 80
