apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nelcaso-core
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - nelcaso.dev.spoletum.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nelcaso-core-dapr
          port: 80
